FROM node:latest

WORKDIR /app

COPY ./mem.txt ./mem
COPY ./code ./code.js
COPY ./input* ./

RUN apt-get update && apt-get install -y util-linux && apt install -y jq

CMD if ls input* 1> /dev/null 2>&1; then for file in input*; do cat "$file" | prlimit --as=$(cat mem) -- node code.js > output_$file; done; else prlimit --as=$(cat mem) -- node code.js > output_input_0.txt; fi; echo -n "{"; first=1; for file in output*; do [ -f "$file" ] && { content=$(awk '{printf "%s\\n", $0}' "$file" | jq -Rs .); [ $first -eq 0 ] && echo -n ","; echo -n "\"$file\":$content"; first=0; }; done; echo "}"